<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Caythe</string>
	<key>fileTypes</key>
	<array>
		<string>mf</string>
		<string>ct</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.manifest.declaration.source.ct</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(group|artifact|version|namespace|import)\s+([^ ]*)</string>
			<key>name</key>
			<string>meta.keyword.manifest.declaration.source.ct</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.using.source.ct</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(use)\s+([^ ]*)</string>
			<key>name</key>
			<string>meta.keyword.use.source.ct</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.source.ct</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.source.ct</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.source.ct</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>builtinTypes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(object|class|annotation|enum|interface)\b</string>
					<key>name</key>
					<string>storage.type.source.ct</string>
				</dict>
			</array>
		</dict>
		<key>class</key>
		<dict>
			<key>begin</key>
			<string>(?=\w?[\w\s]*(?:object|class|annotation|interface|enum)\s+\w+)</string>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.class.end.source.ct</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.source.ct</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#storage-modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.source.ct</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.source.ct</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(object|class|annotation|interface|enum)\s+(\w+)</string>
					<key>name</key>
					<string>meta.class.identifier.source.ct</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>end</key>
					<string>(?={)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.source.ct</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*,?([A-Za-z_]\w*)\b</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.class.begin.source.ct</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.class.body.source.ct</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#method</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storage-modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method-call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtinTypes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#documentation</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.ct</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/\n?</string>
					<key>name</key>
					<string>comment.block.documentation.source.ct</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\{@([^ ]*)\s+(.*)\}</string>
							<key>name</key>
							<string>meta.comment.block.documentation.annotation.source.cs</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.ct</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.source.ct</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|this)\b</string>
					<key>name</key>
					<string>constant.language.source.ct</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.source.ct</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&quot;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.source.ct</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&quot;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.source.ct</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.source.ct</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.source.ct</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|else|for|return|continue|break|switch|case|default|fallthrough)\b</string>
					<key>name</key>
					<string>keyword.control.source.ct</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.ct</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(delegate|property)\b</string>
					<key>name</key>
					<string>keyword.other.source.ct</string>
				</dict>
			</array>
		</dict>
		<key>method</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[\w&lt;].*\s+)(?=[^=]+\()</string>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.method.end.source.ct</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.method.source.ct</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#storage-modifiers</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>([\w.]+)\s*\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.source.ct</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>name</key>
							<string>meta.method.identifier.source.ct</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?=\w.*\s+[\w.]+\s*\()</string>
							<key>end</key>
							<string>(?=[\w.]+\s*\()</string>
							<key>name</key>
							<string>meta.method.return-type.source.ct</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#builtinTypes</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>:\s*(this|base)\s*\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.language.source.ct</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>name</key>
							<string>meta.method.base-call.source.ct</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#builtinTypes</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.method.begin.source.ct</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>name</key>
							<string>meta.method.body.source.ct</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#code</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?!new)(?=[\w&lt;].*\s+)(?=[^=]+\{)</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.property.end.source.ct</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.property.source.ct</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#storage-modifiers</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>([\w.]+)\s*(?={)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.source.ct</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?={)</string>
							<key>name</key>
							<string>meta.method.identifier.source.ct</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?=\w.*\s+[\w.]+\s*\{)</string>
							<key>end</key>
							<string>(?=[\w.]+\s*\{)</string>
							<key>name</key>
							<string>meta.method.return-type.source.ct</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#builtinTypes</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.property.begin.source.ct</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>name</key>
							<string>meta.method.body.source.ct</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#code</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>method-call</key>
		<dict>
			<key>begin</key>
			<string>([\w$]+)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.method.source.ct</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.method-parameters.begin.source.ct</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.method-parameters.end.source.ct</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.method-call.source.ct</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.definition.seperator.parameter.source.ct</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
			</array>
		</dict>
		<key>storage-modifiers</key>
		<dict>
			<key>match</key>
			<string>\b(export|method|public|package|modifiable|override)\b</string>
			<key>name</key>
			<string>storage.modifier.source.ct</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ct</string>
	<key>uuid</key>
	<string>C4C68B17-6345-49F9-83FC-5BACC3B075B6</string>
</dict>
</plist>
